from collections import deque
dq = deque()
dq.append(10)
dq.append(20)
dq.append(30)
print("After append:", dq)
dq.appendleft(5)
dq.appendleft(1)
print("After appendleft:", dq)
right_removed = dq.pop()
print("Removed from right:", right_removed)
print("After pop:", dq)
left_removed = dq.popleft()
print("Removed from left:", left_removed)
print("After popleft:", dq)
